// =============================================================================
// Lab 12: Extracting double-precision numbers from strings
// =============================================================================
// Author: Jaycob
//
// AI assistance summary (Claude):
//   Throughout development I asked Claude conceptual questions ("how do I keep
//   12 together when reading digits one at a time?", "any good name ideas for
//   this flag?", "does the requirements say anything about e^3.2?") and Claude
//   answered without writing code. Claude also ran my code against test cases
//   I provided and reported which ones failed.
//
//   At one point, after many rounds of debugging, I asked Claude directly:
//     "can you fix the bugs in the code and test it untill it works"
//   In response to that single prompt, Claude produced the bug fixes that are
//   now in collectValidChars (the state-flag rewrite) and the validation
//   passes at the bottom of that function, plus the overflow guard in
//   buildNumber. Those AI-generated regions are tagged inline below with
//   [AI-GENERATED] and the triggering prompt.
//
//   Original code by me (Jaycob): characterToDouble, applyExponent, the
//   overall two-function structure, the preDecimal/postDecimal/exponental
//   accumulation logic in buildNumber, printResult, and main.
// =============================================================================

#include <iostream>
#include <iomanip>
#include <cmath>
#include <vector>
#include <string>
using namespace std;

// -----------------------------------------------------------------------------
// characterToDouble  [MY CODE]
//   Converts a single digit character ('0'-'9') to its numeric value.
//   Returns -1 for any non-digit character.
// -----------------------------------------------------------------------------
double characterToDouble(char character) {
    switch (character) {
        case '0': return 0;
        case '1': return 1;
        case '2': return 2;
        case '3': return 3;
        case '4': return 4;
        case '5': return 5;
        case '6': return 6;
        case '7': return 7;
        case '8': return 8;
        case '9': return 9;
        default:  return -1;
    }
}

// -----------------------------------------------------------------------------
// applyExponent  [MY CODE]
//   Multiplies (or divides) input by 10 a total of 'exponent' times.
//   Used to apply the scientific-notation exponent to the parsed base value.
// -----------------------------------------------------------------------------
double applyExponent(double input, bool isPositive, int exponent) {
    if (isPositive) {
        for (int i = 0; i < exponent; i++) input = input * 10;
    } else {
        for (int i = 0; i < exponent; i++) input = input / 10;
    }
    return input;
}

// -----------------------------------------------------------------------------
// collectValidChars
//   First pass of the parser. Walks the input string left-to-right and
//   pushes only the characters that belong to the embedded number into
//   the 'numbers' vector. Returns -1 for invalid patterns, otherwise the
//   number of characters collected.
//
//   Original structure was mine. The state-flag-based rewrite of the loop
//   body and all the post-loop validation passes were generated by Claude
//   in response to my prompt:
//       "can you fix the bugs in the code and test it untill it works"
// -----------------------------------------------------------------------------
int collectValidChars(string input, vector<char> *numbersPtr) {
    vector<char>& numbers = *numbersPtr;
    bool gotSign = false;
    int length = 0;
    int periodCounter = 0;

    // [AI-GENERATED] state flags introduced by Claude to fix bugs where
    // 'e' in unrelated words (like "temp", "hello") was being mistaken for
    // an exponent marker, and where letters between digits weren't triggering
    // invalid. Triggered by: "can you fix the bugs in the code and test
    // it untill it works"
    bool inNumber = false;          // currently inside the number
    bool finishedNumber = false;    // number ended; further digits = INVALID
    bool seenExp = false;           // 'e'/'E' has been processed

    for (int i = 0; i < (int)input.length(); i++) {
        char c = input[i];

        // ---------------- digits ----------------
        if (isdigit(c)) {
            // [AI-GENERATED] check that rejects digits appearing after the
            // number already ended (catches "12a3.45")
            if (finishedNumber) return -1;

            // Capture the base sign — only valid right before the FIRST digit.
            // [AI-GENERATED tweak] added "&& !inNumber" so the '-' after 'e'
            // in scientific notation isn't mistaken for a base sign
            if (not gotSign && !inNumber){
                if (i > 0 && input[i - 1] == '-') {
                    numbers.push_back(input[i - 1]);
                    gotSign = true;
                    length++;
                };
            }

            numbers.push_back(c);
            length++;
            inNumber = true;
            continue;
        }

        // ---------------- decimal point ----------------
        if (c == '.') {
            // [AI-GENERATED] check for trailing-garbage '.'
            if (finishedNumber) continue;
            // [AI-GENERATED] catches "1.2e3.4" (decimal in exponent)
            if (seenExp) return -1;

            periodCounter++;
            numbers.push_back(c);
            length++;
            inNumber = true;
            continue;
        }

        // ---------------- exponent marker ----------------
        // [AI-GENERATED block] entire revised e/E handling logic was produced
        // by Claude. Original version captured ANY e/E in the string, which
        // broke inputs like "temp -98.6F". Triggered by the same prompt.
        if (c == 'e' or c == 'E') {
            // 'e' before any digit is just a letter in some word like
            // "temp" or "hello" — ignore it.
            if (!inNumber) continue;

            // A second 'e' for the same number is part of trailing garbage
            // like "...e+3end". End the number; don't reject.
            if (seenExp) {
                finishedNumber = true;
                inNumber = false;
                continue;
            }

            // Need a digit, '+', or '-' right after the 'e'.
            if (i + 1 >= (int)input.length()) return -1;
            char next = input[i + 1];
            if (next == '+' || next == '-' || isdigit(next)) {
                numbers.push_back(c);
                numbers.push_back(next);
                i++;                  // skip the sign/digit we just consumed
                length += 2;
                seenExp = true;
                continue;
            } else {
                return -1;            // 'e' followed by garbage like "1eX"
            }
        }

        // ---------------- any other character ----------------
        // [AI-GENERATED] mark number as finished when garbage appears.
        // This is what enables the "letters between digits" check above.
        if (inNumber) {
            finishedNumber = true;
            inNumber = false;
        }
    }

    // ===== Post-loop validation [AI-GENERATED entire section] =====
    // Triggered by: "can you fix the bugs in the code and test it untill
    // it works". The original code had no post-loop validation; all of
    // these checks were added by Claude.

    // Must have at least one digit somewhere.
    bool hasDigit = false;
    for (char ch : numbers) {
        if (isdigit(ch)) { hasDigit = true; break; }
    }
    if (!hasDigit) return -1;

    // Multiple decimal points (e.g. "12.34.56") is invalid.
    if (periodCounter > 1) return -1;

    // A double has ~17 digits of precision. More integer digits than that
    // means the value can't be represented faithfully (catches inputs
    // like "9999...9999").
    int intDigits = 0;
    for (int k = 0; k < length; k++) {
        if (numbers[k] == '.' || numbers[k] == 'e' || numbers[k] == 'E') break;
        if (isdigit(numbers[k])) intDigits++;
    }
    if (intDigits > 17) return -1;

    // If we started an exponent, make sure it has at least one digit and
    // contains nothing else after its (optional) sign.
    if (seenExp) {
        int ePos = -1;
        for (int k = 0; k < length; k++) {
            if (numbers[k] == 'e' || numbers[k] == 'E') { ePos = k; break; }
        }
        int k = ePos + 1;
        if (k < length && (numbers[k] == '+' || numbers[k] == '-')) k++;
        bool expHasDigit = false;
        for (; k < length; k++) {
            if (isdigit(numbers[k])) { expHasDigit = true; break; }
            return -1;     // a non-digit appears in exponent
        }
        if (!expHasDigit) return -1;
    }

    // A lone decimal point with no digits on either side (e.g. "-.") is invalid.
    if (periodCounter == 1) {
        int dotPos = -1;
        for (int k = 0; k < length; k++) {
            if (numbers[k] == '.') { dotPos = k; break; }
        }
        bool digitBefore = false, digitAfter = false;
        for (int k = 0; k < dotPos; k++) {
            if (isdigit(numbers[k])) { digitBefore = true; break; }
        }
        for (int k = dotPos + 1; k < length; k++) {
            if (numbers[k] == 'e' || numbers[k] == 'E') break;
            if (isdigit(numbers[k])) { digitAfter = true; break; }
        }
        if (!digitBefore && !digitAfter) return -1;
    }

    return length;
}

// -----------------------------------------------------------------------------
// buildNumber  [MOSTLY MY CODE]
//   Second pass of the parser. Takes the validated character vector from
//   collectValidChars and accumulates the actual double value.
//
//   Approach (mine):
//     - Pre-decimal digits: build by repeated multiply-by-10 and add.
//       e.g. "123" -> 0*10+1=1, 1*10+2=12, 12*10+3=123
//     - Post-decimal digits: divide each new digit by a growing divisor.
//       e.g. ".34" -> 0 + 3/10 = 0.3, 0.3 + 4/100 = 0.34
//     - Exponent digits: build like an integer, then apply via applyExponent.
// -----------------------------------------------------------------------------
double buildNumber(vector<char> *numbersPtr, int length) {
    vector<char>& numbers = *numbersPtr;
    double result = 0.0;
    double preDecimal = 0.0;
    double postDecimal = 0.0;
    int exponental = 0;
    bool seenDecimal = false;
    bool seenExponental = false;
    bool positiveExponental = true;        // [AI-GENERATED tweak] default to true
                                           // (was uninitialized in some paths)
    int divisor = 10;

    for (int i = 0; i < length; i++) {
        if (numbers[i] == '.'){seenDecimal = true; continue;}
        if (numbers[i] == 'e' or numbers[i] == 'E') {seenExponental = true; continue;}

        // Phase 1: pre-decimal portion of the base
        // [AI-GENERATED tweak] added "not seenExponental" guard so exponent
        // chars don't get re-processed as base digits
        if (not seenExponental && not seenDecimal) {
            if (numbers[i] == '-') continue;       // skip the base sign char
            preDecimal = preDecimal * 10 + characterToDouble(numbers[i]);
            continue;
        }

        // Phase 2: post-decimal portion of the base
        if (seenDecimal && not seenExponental) {
            postDecimal = postDecimal + (characterToDouble(numbers[i]) / divisor);
            divisor = divisor * 10;
        }

        // Phase 3: exponent
        if (seenExponental) {
            if (numbers[i] == '+'){positiveExponental = true;  continue;}
            // [AI-GENERATED tweak] added the "positiveExponental = false"
            // assignment — original code had an empty else for negative sign
            if (numbers[i] == '-'){positiveExponental = false; continue;}
            exponental = exponental * 10 + (int)characterToDouble(numbers[i]);
        }
    }

    // [AI-GENERATED block] overflow guard — without this, "1e999" silently
    // produced inf instead of being flagged as invalid. Triggered by:
    // "can you fix the bugs in the code and test it untill it works"
    if (exponental > 308 && positiveExponental && (preDecimal + postDecimal) != 0) {
        return INFINITY;        // signals overflow to extractNumeric
    }

    result = preDecimal + postDecimal;
    result = applyExponent(result, positiveExponental, exponental);
    if (numbers[0] == '-'){result = result * -1;}
    return result;
}

// -----------------------------------------------------------------------------
// extractNumeric
//   Public entry point as required by the spec. Coordinates the two passes
//   and converts overflow / inf / NaN into the sentinel -999999.99.
//
//   Body was mine; the inf/nan/range checks at the bottom were added by
//   Claude as part of the "fix the bugs" prompt.
// -----------------------------------------------------------------------------
double extractNumeric(const string& str) {
    vector<char> numbers;
    int length = collectValidChars(str, &numbers);
    if (length == -1) return -999999.99;

    double result = buildNumber(&numbers, length);

    // [AI-GENERATED] reject inf/nan/out-of-range results.
    if (isinf(result) || isnan(result)) return -999999.99;
    if (result > 1.7e308 || result < -1.7e308) return -999999.99;

    return result;
}

// -----------------------------------------------------------------------------
// printResult  [MY CODE]
//   Formats output per spec: 4 decimal places fixed-point, or the invalid msg.
// -----------------------------------------------------------------------------
void printResult(double result) {
    if (result == -999999.99) {
        cout << "Invalid input: no valid floating-point number found" << endl;
    } else {
        cout << "Extracted number: " << fixed << setprecision(4) << result << endl;
    }
}

// -----------------------------------------------------------------------------
// main  [MY CODE]
//   Repeatedly prompts the user for input until they type END.
// -----------------------------------------------------------------------------
int main() {
    string input;

    while (true) {
        cout << "Enter a string (or 'END' to quit): ";
        getline(cin, input);

        if (input == "END") break;

        double result = extractNumeric(input);
        printResult(result);
    }

    cout << "Program terminated." << endl;
    return 0;
}